server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/juliehuyen/M2-AWOS-FlightReservations-Config
          default-label: main